# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2020 Codefair Semiconductor Technology Co., Ltd.
#		http://www.codefairsemi.com 
#
#

obj-y	:= soc.o clock.o
obj-$(CONFIG_SPL_BUILD)		+= ddr.o
obj-$(CONFIG_WOKOO_DDR3)		+= ddr3.o
